defaults: &defaults
  docker:
    - image: circleci/php:7.2.8-fpm-stretch
  #working_directory: /var/www
version: 2.1
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

        #      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
        #      - run: sudo docker-php-ext-install zip
      #- persist_to_workspace:
      #    root: /var
      #    paths:
      #      - www/
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      #- run: echo $DOTENV | base64 -d > .env.testing
      #- run: echo ./.env.testing
      - run: composer install --ignore-platform-reqs --no-interaction --no-plugins --no-scripts --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      
      # prepare the database
      #- run: touch storage/testing.sqlite
      - run: 
          name: Start 
          command: php artisan migrate --env=testing --database=sqlite --force

      # run tests with phpunit or codecept
      - run:
          name: Run Unit tests
          command: phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
      - run: 
          name: Code Coverage
          command: bash <(curl -s https://codecov.io/bash)

      - run:
          name: Build Docker Image
          command: |
            export TAG=0.1.${CIRCLE_BUILD_NUM}
            export IMAGE_NAME=hsarena/shitty-app:$TAG
            docker build -t $IMAGE_NAME  .
            docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
            docker push $IMAGE_NAME
